% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
  \usepackage{amssymb}
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Homework01},
  pdfauthor={Tanubrata Dey},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Homework01}
\author{Tanubrata Dey}
\date{9/23/2021}

\begin{document}
\maketitle

\hypertarget{homework-1}{%
\section{Homework 1}\label{homework-1}}

\hypertarget{due-092321}{%
\subsection{DUE: 09/23/21}\label{due-092321}}

Please submit your R code and functions in one file.

Remember to comment on your code!

We will use the data file \textbf{expvalues.txt}.

Remember, the first line defines the different experiments and after
that every row is a different gene and its expression (RNA transcript
abundance) values. The first column is the gene name, followed by the
different experiments. First three experiments are replicates of the
\textbf{control} experiments and the last three are replicates for the
\textbf{treatments}.

\hypertarget{descriptive-statistics}{%
\subsubsection{1. Descriptive Statistics}\label{descriptive-statistics}}

\hypertarget{a.-load-the-file-expvalues.txt-into-r-and-call-it-expvalues.}{%
\paragraph{\texorpdfstring{a. Load the file expvalues.txt into R and
call it
\textbf{expvalues}.}{a. Load the file expvalues.txt into R and call it expvalues.}}\label{a.-load-the-file-expvalues.txt-into-r-and-call-it-expvalues.}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Answer here}
\NormalTok{expvalues }\OtherTok{\textless{}{-}} \FunctionTok{read.table}\NormalTok{(}\StringTok{"expvalues.txt"}\NormalTok{) }\CommentTok{\#reading the file expvalues.txt in expvalues variable}
\end{Highlighting}
\end{Shaded}

\hypertarget{b.-create-a-histogram-of-all-values-in-the-columns-control1.-use-the-argument-breaks100-in-the-argument.-what-can-you-conclude-about-the-data}{%
\paragraph{\texorpdfstring{b. Create a histogram of all values in the
columns \textbf{Control1}. Use the argument \textbf{breaks=100} in the
argument. What can you conclude about the
data?}{b. Create a histogram of all values in the columns Control1. Use the argument breaks=100 in the argument. What can you conclude about the data?}}\label{b.-create-a-histogram-of-all-values-in-the-columns-control1.-use-the-argument-breaks100-in-the-argument.-what-can-you-conclude-about-the-data}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Answer here}

\FunctionTok{hist}\NormalTok{(expvalues}\SpecialCharTok{$}\NormalTok{Control1, }\AttributeTok{breaks =} \DecValTok{100}\NormalTok{) }\CommentTok{\#histogram of first column in expvalues variable}
\end{Highlighting}
\end{Shaded}

\includegraphics{Homework01_solved_files/figure-latex/unnamed-chunk-2-1.pdf}

What can you conclude about the data?

The graph above shows that the data are not well distributed and are
biased towards 0, making it hard to visualize the expression data.

\hypertarget{c.-values-can-be-transformed-for-many-reasons.-perform-a-log-transformation-by-simply-taking-the-log2-of-the-values-in-the-column-control1-and-then-create-a-histogram-plot-again.-what-can-you-conclude-about-this-graph}{%
\paragraph{\texorpdfstring{c.~Values can be transformed for many
reasons. Perform a log transformation by simply taking the
\textbf{log2()} of the values in the column \textbf{Control1} and then
create a histogram plot again. What can you conclude about this
graph?}{c.~Values can be transformed for many reasons. Perform a log transformation by simply taking the log2() of the values in the column Control1 and then create a histogram plot again. What can you conclude about this graph?}}\label{c.-values-can-be-transformed-for-many-reasons.-perform-a-log-transformation-by-simply-taking-the-log2-of-the-values-in-the-column-control1-and-then-create-a-histogram-plot-again.-what-can-you-conclude-about-this-graph}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Answer here}
\NormalTok{log2\_Control1 }\OtherTok{\textless{}{-}} \FunctionTok{log2}\NormalTok{(expvalues}\SpecialCharTok{$}\NormalTok{Control1) }\CommentTok{\#taking log2() of the first column of expvalues}
\FunctionTok{hist}\NormalTok{(log2\_Control1, }\AttributeTok{breaks =} \DecValTok{100}\NormalTok{) }\CommentTok{\#plotting histogram of log2 values}
\end{Highlighting}
\end{Shaded}

\includegraphics{Homework01_solved_files/figure-latex/unnamed-chunk-3-1.pdf}

What can you conclude about this graph?

The expression values seem to be better distributed in the log2() graph
because we can see in the above graph that theexpression levels are
between 0 to 15 and are not biased as that one in previous graph where
the curve was in 0. The expression values are well differentiated here
giving us a better idea about the expression data.

\hypertarget{d.-now-that-we-are-convinced-that-taking-the-log2-of-the-values-gives-us-a-better-representation-of-the-distribution-of-the-values-create-a-boxplot-using-the-log2-of-all-the-values.-which-two-samples-look-different-from-the-rest-explain-why.}{%
\paragraph{d.~Now that we are convinced that taking the log2 of the
values gives us a better representation of the distribution of the
values, create a boxplot using the log2 of all the values. Which two
samples look different from the rest? Explain
why.}\label{d.-now-that-we-are-convinced-that-taking-the-log2-of-the-values-gives-us-a-better-representation-of-the-distribution-of-the-values-create-a-boxplot-using-the-log2-of-all-the-values.-which-two-samples-look-different-from-the-rest-explain-why.}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Answer here}
\NormalTok{log2\_expvalues }\OtherTok{\textless{}{-}} \FunctionTok{log2}\NormalTok{(expvalues) }\CommentTok{\#taking log2 of the whole data in variable expvalues}
\FunctionTok{boxplot}\NormalTok{(log2\_expvalues) }\CommentTok{\#making boxplot of the log2() transformed data}
\end{Highlighting}
\end{Shaded}

\includegraphics{Homework01_solved_files/figure-latex/unnamed-chunk-4-1.pdf}
Which two samples look different from the rest? Explain why.

Control1 and Treatment 2 looks different than the rest because these 2
columns shows values below 0, this can be confirmed by seeing the
whiskers in the boxplot that there are many values in both control1 and
treatment2 that are at 0 or below 0, seems to be outliers.

\hypertarget{fold-change-calculation}{%
\subsubsection{2. Fold change
calculation:}\label{fold-change-calculation}}

\hypertarget{a.-the-first-three-columns-are-biological-replicates-of-control-samples-and-last-three-columns-are-treatment-samples.-create-a-factor-called-expgroups-to-represent-this-information.}{%
\paragraph{\texorpdfstring{a. The first three columns are biological
replicates of \textbf{control} samples and last three columns are
\textbf{treatment} samples. Create a factor, called \textbf{expgroups}
to represent this
information.}{a. The first three columns are biological replicates of control samples and last three columns are treatment samples. Create a factor, called expgroups to represent this information.}}\label{a.-the-first-three-columns-are-biological-replicates-of-control-samples-and-last-three-columns-are-treatment-samples.-create-a-factor-called-expgroups-to-represent-this-information.}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Answer here}
\NormalTok{expgroups }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"Control"}\NormalTok{, }\StringTok{"Control"}\NormalTok{, }\StringTok{"Control"}\NormalTok{, }\StringTok{"Treatment"}\NormalTok{, }\StringTok{"Treatment"}\NormalTok{, }\StringTok{"Treatment"}\NormalTok{)) }\CommentTok{\#creating a factor of the columns so that the data is divided into 2 levels}
\end{Highlighting}
\end{Shaded}

\hypertarget{b.-using-the-original-expvalues-not-the-logged-values-calculate-the-average-treatment-and-control-for-each-gene.-save-the-results-in-a-matrix-called-expmeans.-you-can-use-loops-or-apply-functions.-how-many-rows-and-columns-are-there-in-expmeans}{%
\paragraph{\texorpdfstring{b. Using the original expvalues (not the
logged values), calculate the average \textbf{treatment} and
\textbf{control} for each gene. Save the results in a matrix called
\textbf{expmeans}. You can use loops or apply functions. How many rows
and columns are there in
expmeans?}{b. Using the original expvalues (not the logged values), calculate the average treatment and control for each gene. Save the results in a matrix called expmeans. You can use loops or apply functions. How many rows and columns are there in expmeans?}}\label{b.-using-the-original-expvalues-not-the-logged-values-calculate-the-average-treatment-and-control-for-each-gene.-save-the-results-in-a-matrix-called-expmeans.-you-can-use-loops-or-apply-functions.-how-many-rows-and-columns-are-there-in-expmeans}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Answer here}
\FunctionTok{tapply}\NormalTok{(}\FunctionTok{as.numeric}\NormalTok{(expvalues[}\DecValTok{1}\NormalTok{,]), expgroups, mean) }\CommentTok{\#grouping and taking mean of first row}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Control Treatment 
##  254.0256  195.5529
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{expmeans }\OtherTok{\textless{}{-}} \FunctionTok{t}\NormalTok{(}\FunctionTok{apply}\NormalTok{(expvalues, }\DecValTok{1}\NormalTok{, tapply, expgroups, mean)) }\CommentTok{\#creating a variable expmeans that contains the average of control and treatment as a whole}

\FunctionTok{nrow}\NormalTok{(expmeans) }\CommentTok{\#printing number of rows}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 22810
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ncol}\NormalTok{(expmeans) }\CommentTok{\#printing number of columns}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{is.matrix}\NormalTok{(expmeans) }\CommentTok{\#checking if expmeans is a matrix}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

How many rows and columns are there in expmeans?

There are 22810 rows and 2 columns in expmeans.

\hypertarget{c.-for-each-gene-we-want-to-determine-how-much-the-expression-has-changed-in-the-treatment-relative-to-the-expression-in-control.-calculate-the-ratio-of-using-the-treatment-and-control-values-in-expmeans.-save-it-in-a-vector-call-expratio.}{%
\paragraph{c.~For each gene we want to determine how much the expression
has changed in the treatment relative to the expression in control.
Calculate the ratio of using the treatment and control values in
expmeans. Save it in a vector call
expratio.}\label{c.-for-each-gene-we-want-to-determine-how-much-the-expression-has-changed-in-the-treatment-relative-to-the-expression-in-control.-calculate-the-ratio-of-using-the-treatment-and-control-values-in-expmeans.-save-it-in-a-vector-call-expratio.}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Answer here}
\CommentTok{\#expmeans \textless{}{-} as.data.frame(expmeans)}
\CommentTok{\#expratio \textless{}{-} (expmeans$Treatment/expmeans$Control)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Answer here}
\NormalTok{expratio }\OtherTok{=} \FunctionTok{as.vector}\NormalTok{(expmeans[,}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\NormalTok{expmeans[,}\DecValTok{1}\NormalTok{]) }\CommentTok{\#creating a vector expratio that contains the ratio of treatment and control}

\FunctionTok{is.vector}\NormalTok{(expratio) }\CommentTok{\#checking if expratio is a vector}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

\hypertarget{d.-take-the-log2-of-expratio-and-call-it-explog2ratio.-you-have-just-calculated-log-fold-change.}{%
\paragraph{d.~Take the log2 of expratio and call it explog2ratio. You
have just calculated log fold
change.}\label{d.-take-the-log2-of-expratio-and-call-it-explog2ratio.-you-have-just-calculated-log-fold-change.}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Answer here}

\NormalTok{explog2ratio }\OtherTok{\textless{}{-}} \FunctionTok{log2}\NormalTok{(expratio) }\CommentTok{\#creating a variable explog2ratio that save log2() fold change data of the variable expratio}
\end{Highlighting}
\end{Shaded}

\hypertarget{e.-by-taking-the-log2-of-the-expratio-you-have-made-the-values-much-more-symmetric.-positive-values-mean-that-original-ratio-was-greater-than-one-treatment-is-higher-and-a-negative-value-means-the-ratio-was-less-than-one-control-was-higher.-create-a-histogram-of-expratio-to-confirm.}{%
\paragraph{e. By taking the log2() of the expratio you have made the
values much more symmetric. Positive values mean that original ratio was
greater than one (treatment is higher) and a negative value means the
ratio was less than one (control was higher). Create a histogram of
expratio to
confirm.}\label{e.-by-taking-the-log2-of-the-expratio-you-have-made-the-values-much-more-symmetric.-positive-values-mean-that-original-ratio-was-greater-than-one-treatment-is-higher-and-a-negative-value-means-the-ratio-was-less-than-one-control-was-higher.-create-a-histogram-of-expratio-to-confirm.}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Answer here}

\FunctionTok{hist}\NormalTok{(explog2ratio) }\CommentTok{\#creating a histogram of explog2ratio variable that contains fold{-}change for each gene}
\end{Highlighting}
\end{Shaded}

\includegraphics{Homework01_solved_files/figure-latex/unnamed-chunk-11-1.pdf}

\hypertarget{f.-since-our-values-are-in-log2-scale-a-value-of-1-means-the-change-was-2x.-so-a-value-of-1-means-the-value-doubled-and-value-of--1-means-the-value-became-half.-how-many-genes-have-a-log2-fold-change-1-or--1}{%
\paragraph{f.~Since our values are in log2 scale, a value of 1 means the
change was 2x. So a value of 1 means the value doubled, and value of -1
means the value became half. How many genes have a log2 fold change
\textgreater{} 1 OR \textless{} -1
?}\label{f.-since-our-values-are-in-log2-scale-a-value-of-1-means-the-change-was-2x.-so-a-value-of-1-means-the-value-doubled-and-value-of--1-means-the-value-became-half.-how-many-genes-have-a-log2-fold-change-1-or--1}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Answer here}

\FunctionTok{sum}\NormalTok{(explog2ratio }\SpecialCharTok{\textgreater{}} \DecValTok{1} \SpecialCharTok{|}\NormalTok{ explog2ratio }\SpecialCharTok{\textless{}} \SpecialCharTok{{-}}\DecValTok{1}\NormalTok{) }\CommentTok{\#getting number of genes that have a log2 fold change \textgreater{} 1 OR \textless{} {-}1.}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4244
\end{verbatim}

How many genes have a log2 fold change \textgreater{} 1 OR \textless{}
-1 ?

There are 4244 genes that have a log2 fold change \textgreater{} 1 OR
\textless{} -1.

\hypertarget{g.-identify-the-gene-get-the-name-of-the-gene-that-has-the-highest-explog2ratio-and-save-the-name-as-upgene.-a-high-log-fold-change-means-that-the-expression-increased-in-treatment-compared-to-control.}{%
\paragraph{g. Identify the gene (get the name of the gene) that has the
highest explog2ratio and save the name as upGene. A high log fold change
means that the expression increased in treatment compared to
control.}\label{g.-identify-the-gene-get-the-name-of-the-gene-that-has-the-highest-explog2ratio-and-save-the-name-as-upgene.-a-high-log-fold-change-means-that-the-expression-increased-in-treatment-compared-to-control.}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Answer here}

\NormalTok{explog2ratio\_df }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(explog2ratio) }\CommentTok{\#converting explog2ratio data into df and saving it in explog2ratio\_df}

\NormalTok{explog2ratio\_df}\SpecialCharTok{$}\NormalTok{gene\_names }\OtherTok{\textless{}{-}} \FunctionTok{rownames}\NormalTok{(expmeans) }\CommentTok{\#adding genenames as a column in explog2ratio\_df}

\NormalTok{upGene }\OtherTok{\textless{}{-}}\NormalTok{ explog2ratio\_df[}\FunctionTok{which.max}\NormalTok{(explog2ratio\_df}\SpecialCharTok{$}\NormalTok{explog2ratio), ] }\CommentTok{\#finding the gene that has highest explog2ratio and saving it in variable upGene}

\NormalTok{upGene}\SpecialCharTok{$}\NormalTok{gene\_names }\CommentTok{\#getting the genename that has highest explog2ratio}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "248837_at"
\end{verbatim}

\hypertarget{h.-identify-the-gene-get-the-name-of-the-gene-that-has-the-lowest-explog2ratio-and-save-it-as-downgene.-the-lowest-most-negative-log-fold-change-means-the-original-ratio-was-less-than-one-which-means-the-treatment-value-was-much-lower-than-the-control.-so-the-expression-decreased-in-treatment.}{%
\paragraph{h. Identify the gene (get the name of the gene) that has the
lowest explog2ratio and save it as downGene. The lowest (most negative)
log fold change means the original ratio was less than one, which means
the treatment value was much lower than the control. So the expression
decreased in
treatment.}\label{h.-identify-the-gene-get-the-name-of-the-gene-that-has-the-lowest-explog2ratio-and-save-it-as-downgene.-the-lowest-most-negative-log-fold-change-means-the-original-ratio-was-less-than-one-which-means-the-treatment-value-was-much-lower-than-the-control.-so-the-expression-decreased-in-treatment.}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Answer here}

\NormalTok{downGene }\OtherTok{\textless{}{-}}\NormalTok{ explog2ratio\_df[}\FunctionTok{which.min}\NormalTok{(explog2ratio\_df}\SpecialCharTok{$}\NormalTok{explog2ratio), ] }\CommentTok{\#finding the gene that has lowest explog2ratio and saving it in variable upGene}

\NormalTok{downGene}\SpecialCharTok{$}\NormalTok{gene\_names }\CommentTok{\#getting the genename that has lowest explog2ratio}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "250286_at"
\end{verbatim}

\hypertarget{i.-obtain-the-original-expression-values-of-biggene-and-smallgene-from-expvalues-and-plot-them-together-in-a-barplot-side-by-side.-explain-how-the-plot-validates-how-your-analysis.}{%
\paragraph{i. Obtain the original expression values of bigGene and
smallGene from expvalues and plot them together in a barplot side by
side. Explain how the plot validates how your
analysis.}\label{i.-obtain-the-original-expression-values-of-biggene-and-smallgene-from-expvalues-and-plot-them-together-in-a-barplot-side-by-side.-explain-how-the-plot-validates-how-your-analysis.}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Answer here}


\NormalTok{upGene\_values }\OtherTok{\textless{}{-}}\NormalTok{ expvalues[}\FunctionTok{rownames}\NormalTok{(expvalues) }\SpecialCharTok{\%in\%}\NormalTok{ upGene}\SpecialCharTok{$}\NormalTok{gene\_names, ] }\CommentTok{\#filtering out values for upGene and saving it in upGene\_values variable}

\NormalTok{downGene\_values }\OtherTok{\textless{}{-}}\NormalTok{ expvalues[}\FunctionTok{rownames}\NormalTok{(expvalues) }\SpecialCharTok{\%in\%}\NormalTok{ downGene}\SpecialCharTok{$}\NormalTok{gene\_names, ] }\CommentTok{\#filtering out values for downGene and saving it in downGene\_values variable}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{upGene\_values }\CommentTok{\#printing out the upGene values}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           Control1 Control2 Control3 Treatment1 Treatment2 Treatment3
## 248837_at  3.65736  10.4063 15.29166   552.4859   7.231182    130.641
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{downGene\_values }\CommentTok{\#printing out the downGene values}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           Control1 Control2 Control3 Treatment1 Treatment2 Treatment3
## 250286_at 171.7833 213.4973 444.1292   13.39198   5.761501   7.627879
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{upGene\_downGene }\OtherTok{\textless{}{-}} \FunctionTok{rbind}\NormalTok{(upGene\_values,downGene\_values) }\CommentTok{\#adding both upgene and downgene values in a df upGene\_downGene}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{barplot}\NormalTok{(}\FunctionTok{as.matrix}\NormalTok{(upGene\_downGene), }\AttributeTok{beside =}\NormalTok{ T, }\AttributeTok{legend.text =}\NormalTok{ T) }\CommentTok{\#plotting barplot with data of both upGene and downGene side by side}
\end{Highlighting}
\end{Shaded}

\includegraphics{Homework01_solved_files/figure-latex/unnamed-chunk-18-1.pdf}

Explain how the plot validates how your analysis.

Based on the above plot it looks like the upgene and downgene seems to
have pretty different response in control vs treatment. During control
250286\_at gene have higher expression levels whereas 248837\_at gene
have lower expression levels. Now in case of treatment its inverse,
250286\_at gene have lower expression levels whereas 248837\_at gene
have higher expression levels which could mean 250286\_at gene that is
upregulated in control is inhibiting the other gene 248837\_at but by
treatment 250286\_at gene is getting inhibited leading to
over-expression of 248837\_at gene.

\end{document}
